AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model for transcribing audio to docx.
Parameters:
  TranscribeBucketName:
    Type: String
  MaxSpeakers:
    Type: Number
  CommonFilename:
    Type: String

Resources:
  RunTranscriptionJob:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/transcribe/
      Description: 'Runs a transcription job'
      MemorySize: 128
      Timeout: 15
      LoggingConfig:
        LogFormat: JSON
        LogGroup: /aws/lambda/sam-transcribe-RunTranscriptionJob
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures: [x86_64]
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Environment:
        Variables:
          MAX_SPEAKERS: !Ref MaxSpeakers
      Policies:
      # TODO: narrower policies
        - AWSLambdaBasicExecutionRole
        - AmazonTranscribeFullAccess
        - AmazonS3FullAccess
      Events:
        AudioUploaded:
          Type: S3
          Properties:
            Bucket: !Ref TranscribeBucket
            Events:
              - s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: audio/

  ConvertToDocx:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/convert/
      Description: 'Converts a transcribed JSON file into docx'
      MemorySize: 256
      # TODO: param for timeout?
      Timeout: 100
      LoggingConfig:
        LogFormat: JSON
        LogGroup: /aws/lambda/sam-transcribe-ConverToDocx
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures: [x86_64]
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Environment:
        Variables:
          COMMON_FILENAME: !Ref CommonFilename
      Policies:
      # TODO: narrower policies
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
      Events:
        AudioUploaded:
          Type: S3
          Properties:
            Bucket: !Ref TranscribeBucket
            Events:
              - s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: transcribed/

  TranscribeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref TranscribeBucketName

Outputs:
  RunTranscriptionJobArn:
    Description: "Transcription Job runner ARN"
    Value: !Ref RunTranscriptionJob
  TranscribeBucketArn:
    Description: "Bucket for transcriptions"
    Value: !Ref TranscribeBucket
  ConvertToDocxArn:
    Description: "Function which converts JSON into docx"
    Value: !Ref ConvertToDocx