AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model for transcribing audio to docx.

Globals:
  Function:
    Runtime: python3.11
    Handler: app.lambda_handler

Parameters:
  DownloadBucketName:
    Type: String
  UploadBucketName:
    Type: String
  MaxSpeakers:
    Type: Number
  CommonFilename:
    Type: String

Resources:
  RunTranscriptionJob:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/transcribe/
      Description: 'Runs a transcription job'
      MemorySize: 128
      Timeout: 15
      LoggingConfig:
        LogFormat: JSON
        LogGroup: /aws/lambda/sam-transcribe-RunTranscriptionJob
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Environment:
        Variables:
          MAX_SPEAKERS: !Ref MaxSpeakers
          DOWNLOAD_BUCKET_NAME: !Ref DownloadBucketName
      Policies:
      # TODO: narrower policies
        - AWSLambdaBasicExecutionRole
        - AmazonTranscribeFullAccess
        - AmazonS3FullAccess
      Events:
        AudioUploaded:
          Type: S3
          Properties:
            Bucket: !Ref UploadBucket
            Events:
              - s3:ObjectCreated:*

  ConvertToDocx:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/convert/
      Description: 'Converts a transcribed JSON file into docx'
      MemorySize: 256
      Timeout: 120
      LoggingConfig:
        LogFormat: JSON
        LogGroup: /aws/lambda/sam-transcribe-ConvertToDocx
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Environment:
        Variables:
          COMMON_FILENAME: !Ref CommonFilename
      Policies:
      # TODO: narrower policies
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
      Events:
        JSONCreated:
          Type: S3
          Properties:
            Bucket: !Ref DownloadBucket
            Events:
              - s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: transcribed/
                  - Name: suffix
                    Value: .json

  DownloadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DownloadBucketName
      LifecycleConfiguration:
        Rules:
          # TODO: configurable expiration
          - ExpirationInDays: 5
            Id: ExpirationRule
            Status: Enabled

  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref UploadBucketName
      LifecycleConfiguration:
        Rules:
          # TODO: configurable expiration
          - ExpirationInDays: 1
            Id: ExpirationRule
            Status: Enabled

Outputs:
  RunTranscriptionJobArn:
    Description: "Transcription job runner"
    Value: !Ref RunTranscriptionJob
  ConvertToDocxArn:
    Description: "Function which converts JSON into docx"
    Value: !Ref ConvertToDocx
  DownloadBucketArn:
    Description: "Bucket for downloading transcriptions"
    Value: !Ref DownloadBucket
  UploadBucketArn:
    Description: "Bucket for uploading audio files"
    Value: !Ref UploadBucket